### ISSUE TITLE
Autoscaling :: Tuning não é executado se alguma das apps ainda não possui stats de uso de recurso

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/asgard-api#173]
Quando uma das apps envovida no autotunig ainda não tem dados de uso de recurso (CPU **e** RAM) o tuning de todas as outras apps não é feito.

Até onde olhei descobri o seguinte:

`PeriodicStateChecker` chama `app.app_stats = await self.cloud_interface.get_app_stats(app)` https://github.com/B2W-BIT/asgard-api/blob/master/asgard/workers/autoscaler/periodicstatechecker.py#L16

O `get_app_stats()` retorna `None` quando não há dados. Isso é feito no `AppStatsConverter.to_model()`: https://github.com/B2W-BIT/asgard-api/blob/master/asgard/workers/converters/asgard_converter.py#L76

O problema acontece no `DecisionComponent.decide_scaling_app()` pois ele chama, sem checar, `app.app_stats.cpu_usage` e `app.app_stats.mem_usage`. E nesses caso `app.app_stats` é `None`.

**Comment by daltonmatos** [comment]
Fui tentar descobrir porque o `mypy` não pegou esse erro e percebi que o pacote `asgard.workers.models` está sem `__init__.py`. Isso faz com que o `mypy` ignore esse pacote. Depois que adicionei o `__init__.py` ele mostrou o problema:

```
asgard/workers/autoscaler/simple_decision_component.py:20: error: Item "None" of "Optional[AppStats]" has 
no attribute "cpu_usage"
```

Mas mostrou também **muitos** outros problemas. Vejam o output completo:

```
```

**Comment by rockerbacon** [comment]
Além desse módulo, asgard.workers.converters e asgard.clients.apps também estão sem o __init__.py. Como o Lint acusa uma quantidade muito grande de erros que não estavam sendo vistos seria bom tratar em uma issue separada.

**Comment by daltonmatos** [comment]
> Além desse módulo, asgard.workers.converters e asgard.clients.apps também estão sem o **init**.py. Como o Lint acusa uma quantidade muito grande de erros que não estavam sendo vistos seria bom tratar em uma issue separada.

Acho justo. Você pode abrir essa issue por favor?

**Comment by rockerbacon** [comment]
@daltonmatos Problema já corrigido em #175. Pode fechar a issue

**Comment by daltonmatos** [comment]
Maravilha! :tada:
