### ISSUE TITLE
Add travis integration for automatic test running

### ISSUE THREAD

**Issue by diogommartins** [B2W-BIT/asgard-api#18]

**Comment by diogommartins** [comment]
![screen shot 2018-02-14 at 8 34 08 pm](https://user-images.githubusercontent.com/6271498/36231790-7a60a266-11c6-11e8-892c-916fa060c859.png)
@daltonmatos  Você precisa ativar a integração com o travis ou me dar permissão em travis-ci.org

**Comment by ramorim** [comment]
Muito bom!! Uma máquina hein.

**Comment by daltonmatos** [comment]
Como faço essa ativação?

**Comment by diogommartins** [comment]
@daltonmatos  Entra nesse link e ativa pro argard-api: https://travis-ci.org/profile/B2W-BIT
