### ISSUE TITLE
Autoscaling :: Melhorar logs das ações tomadas

### ISSUE THREAD

**Issue by rockerbacon** [B2W-BIT/asgard-api#189]
Atualmente os logs não mostram as informações de maneira particularmente amigável. É preciso alterar os logs para que sejam mais facilmente visualizados e possuam informações claras sobre as ações sendo tomadas.

**Comment by daltonmatos** [comment]
Isso. Acho que podemos ter os seguintes campos:
- `event`: Representa a ação sendo tomada: `autotune`, `autoscale`, etc.
- `appname`: Nome da app onde esse evento aconteceu
- `namespace`: Id da account Asgard. Isso é retirado do noma da app
- `action`: Ação que foi feita: `CPU_SCALE_UP`, `CPU_SCALE_DOWN`, etc.
- `data` (?): Dados adicionais como por exemplo: valor anterior e posterior do atributo que foi mudado.

O que acha @rockerbacon ?

**Comment by Dentxinho** [comment]
Como fica o log hoje? Tem alguns exemplos?


> * `event`: Representa a ação sendo tomada: `autotune`, `autoscale`, etc.
> * `appname`: Nome da app onde esse evento aconteceu
> * `action`: Ação que foi feita: `CPU_SCALE_UP`, `CPU_SCALE_DOWN`, etc.
Acho fundamental esses campos

**Comment by rockerbacon** [comment]
@Atualmente fazemos logs das

> Como fica o log hoje? Tem alguns exemplos?
> 
> > * `event`: Representa a ação sendo tomada: `autotune`, `autoscale`, etc.
> > * `appname`: Nome da app onde esse evento aconteceu
> > * `action`: Ação que foi feita: `CPU_SCALE_UP`, `CPU_SCALE_DOWN`, etc.
> 
> Acho fundamental esses campos

Atualmente fazemos logs contendo:
- id da aplicação;
- parâmetro de CPU a ser aplicado (somente se houver alteração);
- parâmetro de memória a ser aplicado (somente se houver alteração);

**Comment by rockerbacon** [comment]
> Isso. Acho que podemos ter os seguintes campos:
> 
> * `event`: Representa a ação sendo tomada: `autotune`, `autoscale`, etc.
> * `appname`: Nome da app onde esse evento aconteceu
> * `namespace`: Id da account Asgard. Isso é retirado do noma da app
> * `action`: Ação que foi feita: `CPU_SCALE_UP`, `CPU_SCALE_DOWN`, etc.
> * `data` (?): Dados adicionais como por exemplo: valor anterior e posterior do atributo que foi mudado.
> 
> O que acha @rockerbacon ?

No caso do `event` como só possuímos autotuning acho que é um caso de _You Aren't Gonna Need It_. Pela minha sugestão sobre a arquitetura na issue #191 uma decisão de autoscaling faria mais sentido como uma `action` de `INSTANCE_SCALE_UP`/`INSTANCE_SCALE_DOWN`, por exemplo.

Como uma única ação do autoscaler pode alterar mais de um parâmetro da aplicação acredito que poderíamos logar um campo `actions` contendo uma lista de dicionários contendo o identificador da ação e os dados que seriam colocados em  em `data`.

**Comment by pabarros** [comment]
> * `event`: Representa a ação sendo tomada: `autotune`, `autoscale`, etc.
> * `appname`: Nome da app onde esse evento aconteceu
> * `namespace`: Id da account Asgard. Isso é retirado do noma da app
> * `action`: Ação que foi feita: `CPU_SCALE_UP`, `CPU_SCALE_DOWN`, etc.
> * `data` (?): Dados adicionais como por exemplo: valor anterior e posterior do atributo que foi mudado.

Acho ideal. :tada:

**Comment by daltonmatos** [comment]
> Como uma única ação do autoscaler pode alterar mais de um parâmetro da aplicação acredito que poderíamos logar um campo `actions` contendo uma lista de dicionários com o identificador da ação e os dados que seriam colocados em em `data`.

Pode ser. Queria ter o dict o mais flat possível, mas podemos começar assim. Sem problemas.

**Comment by daltonmatos** [comment]
> No caso do `event` como só possuímos autotuning acho que é um caso de _You Aren't Gonna Need It_. Pela minha sugestão sobre a arquitetura na issue #191 uma decisão de autoscaling faria mais sentido como uma `action` de `INSTANCE_SCALE_UP`/`INSTANCE_SCALE_DOWN`, por exemplo.

Penso que ter esse campo já nos deixaria preparado para quando tivermos mais de uma ação, que é quando teremos múltiplos valores para esse campo.

Fazendo ele agora, fica menos coisa pra fazer quando o segundo valor surgir, pois a Enum já vai estar pronta, o nome da event atual já estará pensado (não deixaremos para a pessoa implementando e segunda ação a responsabilidade de pensar no nome da ação que já está pronta) e teremos apenas que adicionar o nome do segundo event.

Por isso pensei em já deixar desde agora.

Pra mim os valores seriam:

 - INSTANCE_SCALE_UP/DOWN
 - INSTANCE_CPU_UP/DOWN
 - INSTANCE_MEM_UP/DOWN

Aliás, nada impede de gerarmos mútiplos logs para uma mesma app. Podemos gerar um linha por ação, se for o caso.
